import React, { useState } from 'react';
import { Code2, Database, Check, Copy, BarChart3 } from 'lucide-react';

export function SQLFlipCard({ sqlQuery, datasetId, executionTime }) {
  const [isFlipped, setIsFlipped] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleCopy = (e) => {
    e.stopPropagation();
    if (!sqlQuery) return;
    navigator.clipboard.writeText(sqlQuery);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full my-3">
      {/* Header Button */}
      <div className="flex items-center justify-between pb-2">
        <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
          <BarChart3 className="w-4 h-4 text-sky-400" />
          Résultats & Visualisation Looker
        </span>

        <button
          type="button"
          onClick={() => setIsFlipped(!isFlipped)}
          className="flex items-center gap-1.5 px-3 py-1 rounded-lg bg-slate-900/80 hover:bg-slate-800 border border-slate-700 text-xs text-sky-300 font-medium transition-all shadow-sm"
        >
          <Code2 className="w-3.5 h-3.5" />
          <span>{isFlipped ? "Voir Graphique Looker" : "Voir Code SQL ⚡"}</span>
        </button>
      </div>

      {/* 3D Flip Card Container */}
      <div className="flip-card w-full">
        <div className={`flip-card-inner ${isFlipped ? 'flipped' : ''}`}>
          
          {/* Recto: Looker KPI & Mock Chart */}
          <div className="flip-recto p-4 rounded-2xl bg-slate-900/90 border border-slate-800 shadow-xl space-y-4">
            <div className="grid grid-cols-2 gap-3">
              <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800">
                <span className="text-[10px] text-slate-400 font-medium block">Ponctualité / Précision</span>
                <span className="text-lg font-bold text-emerald-400">92.4%</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800">
                <span className="text-[10px] text-slate-400 font-medium block">Dataset Source</span>
                <span className="text-xs font-bold text-sky-300 font-mono truncate block">{datasetId || 'bigquery_ds'}</span>
              </div>
            </div>

            {/* Looker Bar Chart Mock */}
            <div className="h-28 flex items-end justify-between gap-3 p-3 rounded-xl bg-slate-950/80 border border-slate-800/80">
              <div className="w-full bg-gradient-to-t from-sky-500 to-blue-600 rounded-t-md transition-all duration-500" style={{ height: '75%' }} />
              <div className="w-full bg-gradient-to-t from-sky-500 to-blue-600 rounded-t-md transition-all duration-500" style={{ height: '90%' }} />
              <div className="w-full bg-gradient-to-t from-sky-500 to-blue-600 rounded-t-md transition-all duration-500" style={{ height: '60%' }} />
              <div className="w-full bg-gradient-to-t from-sky-500 to-blue-600 rounded-t-md transition-all duration-500" style={{ height: '85%' }} />
              <div className="w-full bg-gradient-to-t from-sky-500 to-blue-600 rounded-t-md transition-all duration-500" style={{ height: '95%' }} />
            </div>
          </div>

          {/* Verso: Neon BigQuery SQL Code */}
          <div className="flip-verso p-4 rounded-2xl bg-slate-950 border border-sky-500/40 font-mono text-xs text-sky-200 shadow-2xl space-y-2">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800 text-[11px] text-slate-400">
              <div className="flex items-center gap-1.5">
                <Database className="w-3.5 h-3.5 text-sky-400" />
                <span>Dataset: <strong className="text-white">{datasetId}</strong></span>
              </div>

              <button
                onClick={handleCopy}
                className="flex items-center gap-1 px-2 py-0.5 rounded bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-300 text-[10px]"
              >
                {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                <span>{copied ? "Copié !" : "Copier SQL"}</span>
              </button>
            </div>

            <pre className="overflow-x-auto whitespace-pre-wrap leading-relaxed text-sky-300 p-2 rounded bg-slate-900/90 border border-slate-800">
              <code>{sqlQuery || `-- BigQuery SQL auto-generated by Vertex AI Agent\nSELECT * FROM \`${datasetId || 'default'}\` LIMIT 10;`}</code>
            </pre>
          </div>

        </div>
      </div>
    </div>
  );
}
